name: Release

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "debian/**"

jobs:
  build:
    name: Build Debian package
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git-buildpackage debhelper equivs
          cd /tmp/
          sudo mk-build-deps -i ${GITHUB_WORKSPACE}/debian/control

      - name: Build package
        run: |
          gbp buildpackage \
            --git-ignore-branch \
            --git-upstream-tag="%(version)s" \
            --git-builder="debuild -i -I --no-sign" \
            --git-export-dir=debian/build/
          echo --- debian/build/
          find debian/build/

      - name: Install package
        run: |
          sudo apt-get -y install ./debian/build/deb-s3_*.deb

      - name: Publish package
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
          REPO_SIGNING_KEY_ID: 7D5185B7D5C7DB93EE44A596439B2443AEC7F4A8

        run: |
          aws s3 cp s3://deb-s3-private/deb-s3-repo-key-private.asc - | gpg --import
          for prefix_codename in \
            debian:bullseye \
            ubuntu:jammy \
            ubuntu:kinetic
          do
            debian/build/deb-s3_*.deb \
            --lock \
            --bucket "deb-s3-repo" \
            --prefix "$(cut -d: -f1 <<< "$prefix_codename")" \
            --codename "$(cut -d: -f2 <<< "$prefix_codename")" \
            --s3-region "${AWS_DEFAULT_REGION}" \
            --visibility private \
            --sign "${REPO_SIGNING_KEY_ID}"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: binary package
          path: debian/build/deb-s3_*.deb
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: source package
          path: |
            debian/build/deb-s3_*.debian.tar.*
            debian/build/deb-s3_*.dsc
            debian/build/deb-s3_*.orig.tar.*
          if-no-files-found: error
